# Generated by Django 4.0.3 on 2022-04-26 19:09

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(default='default.png', upload_to='photographer_pics')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='photographer')),
                ('experience', models.CharField(max_length=255)),
                ('devices', models.CharField(max_length=100)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('from_user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user1', to=settings.AUTH_USER_MODEL)),
                ('to_user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
