# Generated by Django 4.0.4 on 2022-05-01 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderRequest',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='photographer',
            new_name='user',
        ),
        migrations.AddField(
            model_name='photographer',
            name='available_daytime',
            field=models.CharField(default='Monday', max_length=100),
            preserve_default=False,
        ),
    ]
