# Generated by Django 4.0.4 on 2022-05-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orderrequest_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='user',
            new_name='photographer',
        ),
    ]
