# Generated by Django 4.0.4 on 2022-05-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_photographer_user_alter_photographer_photographer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='photographer',
        ),
    ]
