# Generated by Django 4.0.4 on 2022-05-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_photographer_photographer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='user',
            new_name='photographer',
        ),
    ]
