# Generated by Django 4.0.4 on 2022-05-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_photographer_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='photographer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
