# Generated by Django 4.0.4 on 2022-05-01 04:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_photographer_photographer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='photographer',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user'),
        ),
    ]
