# Generated by Django 4.0.4 on 2022-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_photographer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='isPhotographer',
            field=models.BooleanField(default=False),
        ),
    ]
