# Generated by Django 4.0.4 on 2022-05-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_photographer_isphotographer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='pimage',
            new_name='photographer_image',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='isPhotographer',
        ),
    ]
