# Generated by Django 4.0.4 on 2022-05-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_pimage_photographer_photographer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='photographer_image',
        ),
    ]
