# Generated by Django 4.0.4 on 2022-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='available_daytime',
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
