# Generated by Django 4.0.3 on 2022-05-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_status_alter_order_id_alter_photographer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user1', to='order.photographer'),
        ),
    ]
